# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-yolox-pytorch',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-yolox-pytorch',
                'lib_path': 'cjm_yolox_pytorch'},
  'syms': {'cjm_yolox_pytorch.core': {'cjm_yolox_pytorch.core.foo': ('core.html#foo', 'cjm_yolox_pytorch/core.py')}}}
